django101/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import social
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',       include('social.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.conf.urls import include, url
from social import views

urlpatterns = [
    url(r'login/', views.social_login, name='login'),
    url(r'$^',     views.index, name='index'),
    url(r'home/', views.home, name='home'),
    url(r'post/add/', views.add_post, name="add_post"),
    url(r'comment/add/', views.add_comment, name='add_comment'),
    url(r'post/delete/(?P<post_id>[0-9]+)/$',   views.delete_post, name="delete_post"),
    url(r'post/edit/(?P<post_id>[0-9]+)/$',   views.edit_post, name="edit_post"),
]

social/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    text = models.TextField()
    poster = models.ForeignKey(User)
    date_time = models.DateTimeField(auto_now=True)
    photo = models.ImageField(null=True, blank=True)

class Comment(models.Model):
    text = models.TextField()
    poster = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    date_time = models.DateTimeField(auto_now=True)   
    class Meta:
        ordering = ['date_time']

social/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.shortcuts import render
from social.models import Post
from django.contrib.auth.decorators import login_required
from social.models import Comment, Post


def index(request):
    return render(request, 'social/index.html')
    
def social_login(request):
   check = _check_post_request(request, ['username', 'password'])
   if check[0]:
       user = authenticate(username=request.POST['username'], password=request.POST['password']) 
       if user is not None:
           login(request, user)
           return HttpResponseRedirect(reverse('social:home'))
       else:
           return HttpResponseBadRequest("The combination of username and password does not exist.")
   else:
       return HttpResponseBadRequest(check[1])

@login_required
def home(request):
    if request.method == 'GET':
        posts = Post.objects.all()
    elif request.method == 'POST':
        check = _check_post_request(request, ['search_terms'])
        if check[0]:
            search_term = request.POST['search_terms']
            posts = Post.objects.filter(text__icontains=search_term)
        else:
            return HttpResponseBadRequest(check[1])
    posts = posts.order_by('-date_time')
    return render(request, 'social/home.html', {'posts': posts, 'user': request.user})

@login_required
def add_post(request):
    check = _check_post_request(request, ['text'])
    if check[0]:
        new_post = Post()
        new_post.text = request.POST['text']
        new_post.poster = request.user
        if 'photo' in request.FILES and request.FILES['photo'] is not None:
            new_post.photo = request.FILES['photo']
        new_post.save()
        return HttpResponseRedirect(reverse('social:home'))
    else:
        return HttpResponseBadRequest(check[1])

def _check_post_request(request, keys):
    # Check that the request method is POST
    if request.method != 'POST':
        return (False, "This method should be called with a POST method!")
    for key in keys:
        # Check that the key exists
        if key not in request.POST:
            return (False, "The POST request should contain a {} field".format(key))
        # Check that the text is not empty
        if not request.POST[key]:
            return (False, "The {} field cannot be empty!".format(key))

    return (True, "Everything is alright!")

@login_required
def add_comment(request):
    check = _check_post_request(request, ['comment', 'post_id'])
    if check[0]:
        new_comment = Comment()
        new_comment.poster = request.user 
        new_comment.text = request.POST['comment']
        try:
            post = Post.objects.get(pk=request.POST['post_id'])
            new_comment.post = post
        except Post.DoesNotExist:
            return HttpResponseBadRequest("There is no Post with id {}".format(request.POST['post_id']))
        new_comment.save()
        return HttpResponseRedirect(reverse('social:home'))
    else:
        return HttpResponseBadRequest(check[1])

@login_required
def delete_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    if request.user != post.poster:
        return HttpResponseForbidden("You can only delete your own posts!")
    else:
        post.delete()
        return HttpResponseRedirect(reverse('social:home'))

@login_required
def edit_post(request, post_id):
    check = _check_post_request(request, ['text'])
    if check[0]:
        post = Post.objects.get(pk=post_id)
        post.text = request.POST['text']
        if 'photo' in request.FILES and request.FILES['photo'] is not None:
            post.photo = request.FILES['photo']
        post.save()
        return HttpResponseRedirect(reverse('social:home'))
    else:
        return HttpResponseBadRequest(check[1])

social/templates/social/home.html
<html>
  <head>
    {% load staticfiles %}
    <title> Social </title>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}"></link>
    <script language="JavaScript" type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  </head>
  <body>
    <div class='container'>

        <div class='row'>
          <!-- New post container -->
          <div class='col-xs-8 col-xs-offset-2'>
            <div class='panel panel-primary' id='new-post'>
              <div class='panel-body'>
                <h1> Write a new post </h1>
                <form action="{% url 'social:add_post' %}" method="post" id='new-post-form' enctype='multipart/form-data'>
                {% csrf_token %}
                  <div class='form-group'>
                    <textarea class='form-control'name='text' form='new-post-form' required placeholder="Write your post here..."></textarea> 
                  </div>
                  <div class='form-group'>
                    <input id='photo-upload' class='form-control' 
                           type='file' name='photo' accept='image/*'>
                    </input>
                    <label for='photo-upload'>Upload a photo</label>
                  </div>
                  <button type='submit' class='btn btn-default'>Post</button>
                </form>
              </div>
            </div>
          </div>

          <!-- Search box -->
          <div class='col-xs-2'>
            <div class='well'>
              <form action="{% url 'social:home' %}" method="post" id='search-bar'>
                {% csrf_token %}
                <div class='form-group'>
                  <input type='text' class='form-control' name='search_terms' required placeholder='Search in posts...'>
                </div>
                <button type='submit' class='btn btn-primary'>Search</button>
              </form>
              <a class='btn btn-success' href="{% url 'social:home' %}">Show all</a>
            </div>
          </div>
        </div>

        <!-- Previous posts container -->
        <div class='row'>
            <div class='col-xs-8 col-xs-offset-2'>
              {% for post in posts %}
                <div class='panel-heading'>
                  <h4>{{post.poster.username}}</h4>
                  <h4 class='small'>
                    posted on {{post.date_time}}
                    {% if post.poster == user %}
                    <form action="{% url 'social:delete_post' post.id %}" method="post" id='delete-post'>
                      {% csrf_token %}
                      <button type='submit'title='delete post' class='glyphicon glyphicon-trash pull-right'></button>
                    </form>
                    {% endif %}
                  </h4>
                </div>
                <div class='panel-body'>
                  <form action="{% url 'social:edit_post' post.id %}" method="post" id='edit-post'>
                   
                      <div id="post_text">
                        <p class='lead'>{{post.text}}</p>
                      </div>
                      <div id="edit_text" style="display:none;">
                        <input type='text' required class='lead' id="edit_text" value="{{post.text}}" name="text"></input>
                      </div>
                      
                      {% if post.poster == user %}
                      {% csrf_token %}
                      <span type='none' title='edit-post-btn' id="edit-post-btn" class='glyphicon glyphicon-edit pull-right'></span>
                      <button type='submit'title='save-post-btn' id="save-post-btn" class='glyphicon glyphicon-floppy-disk pull-right' style="display:none;"></button>
                      {% endif %}
                  </form>
                </div>
                {% if post.photo %}
                    <div class='col-xs-10 col-xs-offset-1'>
                      <img class='img-responsive center-block img-rounded' src={{post.photo.url}}/>
                    </div>
                {% endif %}
                <div class='row'>
                  <div class='col-xs-10 col-xs-offset-1'>
                    <ul class='list-group'>
                      {% for comment in post.comment_set.all %}
                      <li class='list-group-item'> 
                        {{comment.text}} - {{comment.poster.username}} ({{comment.date_time}}) 
                      </li>
                      {% endfor %}
                    </ul>
                    <form action="{% url 'social:add_comment' %}" method="post">
                    {% csrf_token %}
                      <div class='form-group'>
                        <input class='form-control' type='text' name='comment' required placeholder="Write your comment here..."/>
                      </div>
                      <input type='hidden' name='post_id' value={{post.id}} />
                      <button class='btn btn-default' type='submit'>Submit</button>
                    </form>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
        </div>
    </div>
    
    <script type="text/javascript" language="JavaScript">
    $('#edit-post-btn').on('click',function(){
        if($('#post_text').css('display')!='none'){
            $('#edit_text').show().siblings('div').hide();
            $('#save-post-btn').show().siblings('span').hide();
        }
    });
    </script>
  </body>
</html>

social/templates/social/index.html
<html>
  <head>
    {% load staticfiles %}
    <title> Welcome to Social! </title>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}"></link>
  </head>
  <body role='document'>
    <div class="container">
      <div class='jumbotron'>
        <h1> Welcome to Social, the least useful social network! </h1>
      </div>
      <div class='row'>
        <div class='col-xs-8 panel panel-default'>
          <div class='panel-body'>
            <p> Social is a minimalistic social network that allows you to share
            writings and pictures with the world. Don't bother with friends, share
            with everyone!
            </p>
          </div>
        </div>
        <div class='col-xs-4'>
          <h2> Please sign in to continue </h2>

          <form action="{% url 'social:login' %}" method="post">
            {% csrf_token %}
            <div class='form-group'>
              <label for="username-input">Username</label>
              <input type="text" class="form-control" required name="username" id="username-input"> 
            </div>
            <div class='form-group'>
              <label for="password-input">Password</label>
              <input type="password"  class="form-control"  required name="password" id="password-input"> 
            </div>
            <button type="submit" class="btn btn-primary">Log in</button>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>